# Generated by Django 2.2.6 on 2019-11-04 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewelname', models.CharField(max_length=20)),
                ('jewelimg', models.ImageField(blank=True, upload_to='jewel_image')),
                ('smalldesc', models.TextField(null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.IntegerField()),
                ('About', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=20)),
                ('storephone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'owner'), (2, 'customer')], default=1)),
                ('place', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone_no', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jewelname', models.ManyToManyField(to='shopapp.Jewel')),
            ],
        ),
    ]
