# Generated by Django 2.2.6 on 2019-11-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Profile')),
                ('jewelname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Jewel')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
